[server]
#port = 4446

[node]
detect-drivers = false
[[node.driver-configuration]]
display-name = "Firefox node"
stereotype = "{\"browserName\": \"firefox\"}"
max-sessions = 5
webdriver-executable = './drivers/geckodriver.exe'